Sarah search fns Merge to Main
webdev-cinematiq/cinematiq pull request #26
Opened 2024-08-08 16:13 UTC by spgallant

Search functionality pulling from TMDB API. Links to search/movie.id and persists search term on refresh and when clicking back from a specific movie detail (result) page.

![image](https://github.com/user-attachments/assets/a747ab8e-9709-480b-8550-cecb5cf4ecd6)

![image](https://github.com/user-attachments/assets/4b9aae37-4eb6-4694-a63e-6590d39869d7)

![image](https://github.com/user-attachments/assets/662f6d52-404f-4854-b283-7204f312a748)

2024-08-08 18:25 UTC, maikkatko approved these changes
Nice work! Looks really good

2024-08-08 18:36 UTC, nancyonyejiaka requested changes
before you merge:
- clicking on a search result should link to `/film/details/movie.id`

2024-08-09 00:15 UTC, spgallant commented on src/components/main/Search/index.tsx
> +            <Link key={movie._id} to={`/film/details/${movie.id}`} className="card-link">
Llink fixed!

2024-08-09 00:33 UTC, maikkatko approved these changes
good to go

2024-08-09 01:11 UTC, nancyonyejiaka approved these changes
nice work!!

2024-08-09 03:53 UTC, merged